// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.2
//   protoc               v3.21.12
// source: proto/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "transaction";

export enum MessaageType {
  AUTHORIZATION = 0,
  CLEARING = 1,
  UNRECOGNIZED = -1,
}

export enum AckStatus {
  SUCCESS = 0,
  FAILED = 1,
  UNRECOGNIZED = -1,
}

export enum Provider {
  PSP1 = 0,
  PSP2 = 1,
  UNRECOGNIZED = -1,
}

export enum TransactionStatus {
  PENDING = 0,
  SUCCESSFUL = 1,
  UNRECOGNIZED = -1,
}

export enum CardSchema {
  VISA = 0,
  MASTER_CARD = 2,
  AMERICAN_EXPRESS = 3,
  MADA = 4,
  MEZA = 5,
  UNRECOGNIZED = -1,
}

export interface TransactionEvent {
  type: MessaageType;
  reference: string;
  currency: string;
  amount: number;
  fractionalDigits: number;
  feesCurrency: string;
  feesAmount: number;
  feesFractionalDigits: number;
  providerEventTime: Date | undefined;
  provider: Provider;
  cardToken: string;
  eventId: string;
}

export interface Ack {
  status: AckStatus;
  eventTime: Date | undefined;
}

export interface Transaction {
  id: string;
  total: Money | undefined;
  status: TransactionStatus;
  cardDetails: CardDetails | undefined;
  reference: string;
}

export interface Money {
  amount: number;
  fractionalDigits: number;
  currency: string;
}

export interface TransactionHistoryResponse {
  transactions: Transaction[];
  currentTime: Date | undefined;
}

export interface CardDetails {
  censoredCardNumber: string;
  cardSchewma: CardSchema;
}

export interface TransactionHistoryRequest {
  userId: string;
}

export const TRANSACTION_PACKAGE_NAME = "transaction";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface TransactionServiceClient {
  sendTransactionEvent(request: TransactionEvent): Observable<Ack>;

  getTransactionHistory(request: TransactionHistoryRequest): Observable<TransactionHistoryResponse>;
}

export interface TransactionServiceController {
  sendTransactionEvent(request: TransactionEvent): Promise<Ack> | Observable<Ack> | Ack;

  getTransactionHistory(
    request: TransactionHistoryRequest,
  ): Promise<TransactionHistoryResponse> | Observable<TransactionHistoryResponse> | TransactionHistoryResponse;
}

export function TransactionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendTransactionEvent", "getTransactionHistory"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TransactionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRANSACTION_SERVICE_NAME = "TransactionService";
